
// This file has been generated by the GUI designer. Do not modify.
public partial class Fotos
{
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Button Abrir;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget Fotos
		this.Name = "Fotos";
		this.Title = global::Mono.Unix.Catalog.GetString ("Fotos");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowGrow = false;
		// Container child Fotos.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.Abrir = new global::Gtk.Button ();
		this.Abrir.CanFocus = true;
		this.Abrir.Name = "Abrir";
		this.Abrir.UseUnderline = true;
		this.Abrir.Label = global::Mono.Unix.Catalog.GetString ("Abrir");
		this.fixed2.Add (this.Abrir);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.Abrir]));
		w1.X = 154;
		w1.Y = 117;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 396;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Abrir.Clicked += new global::System.EventHandler (this.On_clicked);
	}
}
